### ISSUE TITLE
注册了dll后还是无法运行

### ISSUE THREAD

**Issue by ghost** [yangyuan/meow#3]
编译通过，注册dll后，列表里能出现输入法，但是无法调用，而且会造成Explorer崩溃。。求教是做错了什么吗？

**Comment by yangyuan** [comment]
我好像并没有公布该输入法的安装方式。
从流程来看，缺少一个操作，即拷贝输入法的附加资源，也就是皮肤和词库。
我也没有公开过词库的文件。

Close 掉，因为这个项目会被重构。
